### PR TITLE
Fix severe compression bug introduced by #97

### LINKED ISSUE #98: Improve brotli compression performance
There is significant performance loss in #97 when client requests brotli compression.

I'd like to find a way to improve it. At least make it as fast as commit 7113041.

[Benchmark](https://github.com/weihanglo/sfz/pull/97#issuecomment-1245448766)

|         | master branch 7113041                                                                                                                                                                                                                                                                                                                                        | feature/issue-33 2ee86cb                                                                                                                                                                                                                                                                                                                                       |
|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| br      | Running 10s test @ http://localhost:5000/Cargo.toml<br>  2 threads and 10 connections<br>  Thread Stats   Avg      Stdev     Max   +/- Stdev<br>    Latency     2.82ms  206.74us  11.20ms   86.73%<br>    Req/Sec     1.78k    34.26     1.84k    83.50%<br>  35471 requests in 10.00s, 54.16MB read<br>Requests/sec:   **3545.80**<br>Transfer/sec:      5.41MB | Running 10s test @ http://localhost:5000/Cargo.toml<br>  2 threads and 10 connections<br>  Thread Stats   Avg      Stdev     Max   +/- Stdev<br>    Latency     5.50ms    2.16ms  26.19ms   71.38%<br>    Req/Sec     0.92k    65.42     1.03k    78.50%<br>  18233 requests in 10.01s, 17.01MB read<br>Requests/sec:   1821.76<br>Transfer/sec:      1.70MB   |

### PR DESCRIPTION
**Pull request by henry40408**
closes #98 

# How to reproduce

- Prepare a large file, e.g. [Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley](https://www.gutenberg.org/ebooks/84), whose size should be greater than 4KB. Save it as `x.txt`.
- Check out master 70b431a.
- `cargo run`
- `curl --compressed http://localhost:5000/x.txt`

A error like `curl: (23) Failed reading the chunked-encoded stream` will occur and only first 4KB content of file will be returned.

# Root cause

https://github.com/weihanglo/sfz/blob/70b431ac3c272b2d0e060c34eb9593577bc14703/src/server/serve.rs#L416-L419

Maybe the body stream isn't split like how I expected, so only the first item of stream get compressed and returned then the rest are dropped. Since the buffer of file stream is 4KB, it might explain why only the first 4KB will be returned:

https://github.com/weihanglo/sfz/blob/70b431ac3c272b2d0e060c34eb9593577bc14703/src/server/send.rs#L160

# Solution

- I replace `compress` with `async-compression`.
- Compared to https://github.com/weihanglo/sfz/pull/97#issuecomment-1245448766 , there is no significant performance improvement or loss when client enables deflate or gzip.
- When it comes to brotli, compression level and response time are highly relevant, so this pull request also resolves #98 .

| brotli        | level = 6                                                                                                                                                                                                                                                                                                                                                    | level = 0, fastest                                                                                                                                                                                                                                                                                                                                           |
|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| benchmark     | Running 10s test @ http://localhost:5000/Cargo.toml<br>  2 threads and 10 connections<br>  Thread Stats   Avg      Stdev     Max   +/- Stdev<br>    Latency     5.45ms    2.20ms  23.10ms   72.66%<br>    Req/Sec     0.93k    79.59     1.06k    70.00%<br>  18434 requests in 10.01s, 18.09MB read<br>Requests/sec:   1841.70<br>Transfer/sec:      1.81MB | Running 10s test @ http://localhost:5000/Cargo.toml<br>  2 threads and 10 connections<br>  Thread Stats   Avg      Stdev     Max   +/- Stdev<br>    Latency     2.97ms    1.09ms  19.27ms   69.77%<br>    Req/Sec     1.70k   110.24     3.07k    96.52%<br>  33932 requests in 10.10s, 38.96MB read<br>Requests/sec:   3359.58<br>Transfer/sec:      3.86MB |
| response size (1561) | 700 (44%)                                                                                                                                                                                                                                                                                                                                                    | 875 (56%)                                                                                                                                                                                                                                                                                                                                                    |

- Another example: [Pride and Prejudice by Jane Austen](https://www.gutenberg.org/ebooks/1342)

| brotli        | level = 6                                                                                                                                                                                                                                                                                                                                                                                                           | level = 0, fastest                                                                                                                                                                                                                                                                                                                                             |
|---------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| benchmark     | Running 10s test @ http://localhost:5000/1342-0.txt<br>  2 threads and 10 connections<br>  Thread Stats   Avg      Stdev     Max   +/- Stdev<br>    Latency     1.30s   432.24ms   1.79s    76.92%<br>    Req/Sec     4.71      3.89    20.00     78.57%<br>  68 requests in 10.01s, 16.04MB read<br>  Socket errors: connect 0, read 0, write 0, timeout 3<br>Requests/sec:      6.79<br>Transfer/sec:      1.60MB | Running 10s test @ http://localhost:5000/1342-0.txt<br>  2 threads and 10 connections<br>  Thread Stats   Avg      Stdev     Max   +/- Stdev<br>    Latency   880.53ms  337.25ms   1.51s    68.52%<br>    Req/Sec     6.25      4.69    30.00     89.47%<br>  108 requests in 10.01s, 42.28MB read<br>Requests/sec:     **10.78**<br>Transfer/sec:      4.22MB |
| response size (798774) | 246517 (30%)                                                                                                                                                                                                                                                                                                                                                                                                        | 405123 (50%)                                                                                                                                                                                                                                                                                                                                                   |

### CODE REVIEW

File: src/http/content_encoding.rs [hunk 1]
```diff
@@ -123,22 +125,22 @@ pub fn get_prior_encoding<'a>(accept_encoding: &'a HeaderValue) -> &'static str
...
-    let mut buf = BytesMut::zeroed(4_096);
-    let read_bytes = match encoding {
-        BR => brotli::CompressorReader::new(data, 4096, 6, 20).read(&mut buf[..])?,
-        GZIP => GzEncoder::new(data, Compression::default()).read(&mut buf[..])?,
-        DEFLATE => DeflateEncoder::new(data, Compression::default()).read(&mut buf[..])?,
-        _ => return Err(io::Error::new(io::ErrorKind::Other, "Unsupported Encoding")),
-    };
-    buf.truncate(read_bytes);
-    Ok(buf.freeze())
+pub fn compress_stream(
```
Comment (weihanglo) [inline src/http/content_encoding.rs:131]: Could we provide a doc comment for this function?

File: src/http/content_encoding.rs [hunk 2]
```diff
@@ -123,22 +125,22 @@ pub fn get_prior_encoding<'a>(accept_encoding: &'a HeaderValue) -> &'static str
...
+    input: impl Stream<Item = io::Result<Bytes>> + std::marker::Send + 'static,
```
Comment (weihanglo) [inline src/http/content_encoding.rs:132]: I believe `Send` is in the prelude.

```suggestion
    input: impl Stream<Item = io::Result<Bytes>> + Send + 'static,
```

File: src/http/content_encoding.rs [hunk 3]
```diff
@@ -241,20 +243,27 @@ mod t_prior {
 #[cfg(test)]
 mod t_compress {
     use super::*;
+    use bytes::Bytes;
```
Comment (weihanglo) [inline src/http/content_encoding.rs:249]: Could be removed.

```suggestion
```

**Review by weihanglo — COMMENTED** [review]
Nice rework! I am fine with lowering brotli compression level.

Just some nits, nothing prominent so far. Thank you!

File: src/http/content_encoding.rs (hunk 3 above)
Comment (henry40408) [reply src/http/content_encoding.rs]: removed on 166e6e7

File: src/http/content_encoding.rs (hunk 2 above)
Comment (henry40408) [reply src/http/content_encoding.rs]: I shouldn't always rely on rust-analyzer and code actions, eh? 😅 fixed on 166e6e7

File: src/http/content_encoding.rs (hunk 1 above)
Comment (henry40408) [reply src/http/content_encoding.rs:137]: Method doc comment added on 5c96c8d

File: src/http/content_encoding.rs [hunk 4]
```diff
@@ -122,30 +128,28 @@ pub fn get_prior_encoding<'a>(accept_encoding: &'a HeaderValue) -> &'static str
...
+/// Compress data stream.
 ///
 /// # Parameters
 ///
-/// * `data` - Data to be compressed.
-/// * `encoding` - Only support `br`, `gzip`, `deflate` and `identity`.
-pub fn compress(data: &[u8], encoding: &str) -> io::Result<Vec<u8>> {
-    use std::io::prelude::*;
-    let mut buf = Vec::new();
+/// * `input` - [`futures::stream::Stream`](futures::stream::Stream) to be compressed e.g. [`hyper::body::Body`](hyper::body::Body).
```
Comment (weihanglo) [inline src/http/content_encoding.rs:135]: One trick is that 

```
[`YourType`]
```

is effective to generating an intra doc link. [^1]

Also, A shorter type looks nice, at least the readability of the source is better.


```suggestion
/// * `input` - [`futures::Stream`] to be compressed, e.g. [`hyper::Body`].
```

[^1]: https://rust-lang.github.io/rfcs/1946-intra-rustdoc-links.html#implied-shortcut-reference-links

Comment (henry40408) [reply src/http/content_encoding.rs]: Applied on 2550654

**Review by weihanglo — APPROVED** [review]
Thank you for getting this job done!
